export const HomeObjThree = {
  id: "contact",
  lightBackground: false,
  lightText: true,
  // lightTextDescription: false,
  topLine: "Generel information",
  headline: "Mobil - Email - Adresse",
  description0: "Mobil - 29217899",
  description: "Email - lassebjoernmosel@gmail.com",
  description1: "Adresse - Bogensegade 1, 1.th 8000 Aarhus C",
  description2: "",
  buttonLabel: "Mere information",
  buttonLabelGotoHome: "Forside",
  imgStart: false,
  img: require("../../images/svg-9.svg").default,
  alt: "Paper",
  dark: false,
  primary: true,
  darkText: false,
};
